apiVersion: v1
kind: Pod
metadata:
  name: teamnavigator
  namespace: auxtools
  labels:
    app: teamnavigator
    app.kubernetes.io/area: auxtools
    app.kubernetes.io/name: teamnavigator

spec:
  containers:
  - name: teamnavigator
    image: ringlerregistry.azurecr.io/auxtools/teamnavigator:latest
    ports:
      - containerPort: 8501